-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 09:16:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cultupaz
-- -----------------------------------------------------
DROP DATABASE IF EXISTS db_cultupaz;
-- -----------------------------------------------------
-- Schema db_cultupaz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cultupaz` DEFAULT CHARACTER SET utf8 ;
USE `db_cultupaz` ;

-- -----------------------------------------------------
-- Table `db_cultupaz`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`tipo_usuarios` (
  `idTipo` INT NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cultupaz`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(20) UNIQUE NOT NULL,
  `ficha` VARCHAR(30) NULL,
  `genero` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `tipoDocumento` VARCHAR(60) NOT NULL,
  `numeroDocumento` VARCHAR(20)UNIQUE NOT NULL,
  `usuario` VARCHAR(45)UNIQUE  NULL,
  `correo` VARCHAR(50) UNIQUE NOT NULL,
  `passw` VARCHAR(200) NOT NULL,
  `estadoUsuario` BOOLEAN NOT NULL DEFAULT TRUE,
  `idTipo` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fk_usuarios_tipo_usuarios1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `db_cultupaz`.`tipo_usuarios` (`idTipo`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cultupaz`.`muro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`muro` (
  `idMuro` INT NOT NULL AUTO_INCREMENT,
  `imagen_muro` VARCHAR(50) NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `done` TINYINT NOT NULL,
  `createAt` TIMESTAMP(6) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMuro`)

    )
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `db_cultupaz`.`muro_usuarios` (
  `idUsuario` INT NOT NULL,
  `idMuro` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `idMuro`),
  FOREIGN KEY (`idUsuario`) REFERENCES `db_cultupaz`.`usuarios` (`idUsuario`),
  FOREIGN KEY (`idMuro`) REFERENCES `db_cultupaz`.`muro` (`idMuro`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_cultupaz`.`juegos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`juegos` (
  `idJuegos` INT NOT NULL AUTO_INCREMENT,
  `nombre_juego` VARCHAR(45) NOT NULL,
  `puntaje` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idJuegos`),
    FOREIGN KEY (`idUsuario`)
    REFERENCES `db_cultupaz`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cultupaz`.`artesanias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`artesanias` (
  `idartesanias` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
      `imagen`  blob NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idartesanias`)

    )
ENGINE = InnoDB;
-- -----------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`usuarios_artesanias` (
  `idartesanias` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idartesanias`, `idUsuario`),
  FOREIGN KEY (`idartesanias`) REFERENCES `db_cultupaz`.`artesanias` (`idartesanias`),
  FOREIGN KEY (`idUsuario`) REFERENCES `db_cultupaz`.`usuarios` (`idUsuario`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cultupaz`.`idasistencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`asistencias` (
  `idasistencia` INT NOT NULL AUTO_INCREMENT,
  `descripcion_asistencia` VARCHAR(200) NULL,
  `idEvento` INT NOT NULL,
  PRIMARY KEY (`idasistencia`)
   
 
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cultupaz`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cultupaz`.`eventos` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `tema_evento` VARCHAR(60) NOT NULL,
  `descripcion_evento` VARCHAR(100) NOT NULL,
  `fecha_evento` DATE NOT NULL,
  `idasistencia` INT NOT NULL,
   `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEvento`)

) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `db_cultupaz`.`asistencias_eventos` (
  `idasistencia` INT NOT NULL,
  `idEvento` INT NOT NULL,
   `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idasistencia`, `idEvento`),
  FOREIGN KEY (`idasistencia`) REFERENCES `db_cultupaz`.`asistencias` (`idasistencia`),
  FOREIGN KEY (`idEvento`) REFERENCES `db_cultupaz`.`eventos` (`idEvento`),
    FOREIGN KEY (`idUsuario`) REFERENCES `db_cultupaz`.`usuarios` (`idUsuario`)
) ENGINE = InnoDB;








SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

